package edu.ctu.storykeeperdata.model;

public enum Category {
    FICTION, NONFICTION, FANTASY, ACTION, HORROR, GRAPHICNOVEL, ROMANCE, SCIFI, SHORTSTORY, SUSPENSE, COOKBOOK, HISTORY, POETRY, SELFHELP, TRUECRIME
}
